### ISSUE TITLE
Restart loop if module failes to start

### ISSUE THREAD

**Issue by dbeuchler** [PHOENIXCONTACT/MORYX-Core#53] opened 2020-10-21 08:43 UTC
**Describe the bug**

![image](https://user-images.githubusercontent.com/920832/96695569-14c80700-138a-11eb-88f8-fce96ecf28f2.png)

**To Reproduce**
Throw exception on start of module

**Expected behavior**
The module should just fail

**Comment by dbeuchler** [comment] 2020-10-22 07:19
@mmarkwort do you have any idea? Before a few weeks i can remember that you checked this out ;-)

**Comment by mmarkwort** [comment] 2020-10-22 08:14
I think that is the reported bug I could not reproduce in that time. I fixed in https://github.com/PHOENIXCONTACT/MORYX-Platform/pull/15 another aspect of error behavior on module start.

**Comment by mmarkwort** [comment] 2020-10-22 08:15
If you can reproduce that I could fix the bug.

**Comment by dbeuchler** [comment] 2020-10-22 09:13
Steps to reproduce: 

1. Reference Module A by Facade in Module B
2. Fail Module A at start

Module B tries to start Module A a second time

**Comment by mmarkwort** [comment] 2020-10-22 09:23
Ok, I will have a look on this

**Comment by dbeuchler** [comment] 2020-10-22 09:32
thats great! Thank you

**Comment by Toxantron** [comment] 2020-10-22 11:48
I took a look a while back but simply forgot. The Problem is the ModuleStarter starts all dependencies of a module. So in case of the ResourceManager for every dependent it calls `Start` again.

In Platform 2.7 the ModuleManager reacted to the state events and checked if anything could be started. I think the Platform3 refactoring replaced some of that logic.

**Comment by mmarkwort** [comment] 2020-11-08 18:13
@dbeuchler 
I tried to reproduce the behavior but I did fail. I added a `throw new NotImplementedException()` to `OnInitialize()` of the `TestModule` and I did not get the expected behavior. I also tested that in the `OnStart()` function.

**Comment by Toxantron** [comment] 2020-11-09 06:04
@mmarkwort I took a look as well and can confirm, that this can not be reproduced in the Platform alone. However it happens quite reliable in the *ControlSystem*. I will try to isolate which conditions cause it.

**Comment by mmarkwort** [comment] 2020-11-09 06:33
Thank you

**Closed** 2022-03-29 07:05 UTC
Labels: bug
